name: Clixon Controller CI

on:
  push:
    branches: [ main, docker ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build clixon controller container
      run: (git clone https://github.com/clicon/clixon-controller.git && cd clixon-controller/docker/ && git checkout docker && docker build -t clixon-controller .)
# 2)  Run tests
    - name: Start devices
      run: cd clixon-controller/test; ./start-devices.sh
    - name: Get container addresses
      run: cd clixon-controller/test; CONTAINERS=`./containers.sh`; echo "CONTAINERS=$CONTAINERS" >> $GITHUB_ENV
    - name: Start controller container
      run: cd clixon-controller/test; ./start-controller.sh
    - name: Run test-change-both
      run: cd clixon-controller/test; CONTROLLERS=${{ env.controllers }} PREFIX=sudo ./test-change-both.sh
    - name: Run test-change-ctrl-push
      run: cd clixon-controller/test; PREFIX=sudo ./test-change-ctrl-push.sh
    - name: Run test-change-device-diff
      run: cd clixon-controller/test; PREFIX=sudo ./test-change-device-diff.sh
    - name: Run test-cli-edit-commit-push
      run: cd clixon-controller/test; ./test-cli-edit-commit-push.sh
    - name: Run test-service
      run: cd clixon-controller/test; PREFIX=sudo ./test-service.sh
    - name: Run test-yanglib
      run: cd clixon-controller/test; PREFIX=sudo ./test-yanglib.sh
